[workspace]
authors = ["Mikkel Roald-Arb√∏l <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "Belay-Paper"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.26,<2"
python = ">=3.14.0,<3.15"
belay = ">=0.28.0,<0.29"
